#Feedback data used by autonomy routing
#RPM of drum 
float32 drumRPM
#position of lift (WIP - not sure how this will be implemented)
float32 liftPos

#robot speed - not sure if these will be usede
float32 leftTreadRPM
float32 rightTreadRPM

#additional info to be displayed in app
float32 liftCurrent
float32 drumCurrent

#WIP
float32 leftStorageWeight
float32 rightStorageWeight
float32 storagePos
string rightTreadFault
string leftTreadFault
string drumFault
string liftFault
string storageFault
